# Generated by Django 4.1.7 on 2023-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devoluciones',
            fields=[
                ('codigoDevolucion', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('codigoFactura', models.PositiveIntegerField()),
                ('cliente', models.PositiveIntegerField()),
                ('productos', models.CharField(max_length=1000)),
                ('cantidadDevolver', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=1000)),
                ('estadoDevolucion', models.CharField(choices=[('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('ESPERANDO', 'Esperando')], default='ESPERANDO', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('codigoFactura', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cliente', models.PositiveIntegerField()),
                ('fechaPedido', models.DateField()),
                ('productos', models.CharField(max_length=1000)),
                ('cantidad', models.PositiveIntegerField()),
                ('precioTotal', models.DecimalField(decimal_places=1, max_digits=10)),
                ('metodoPago', models.CharField(max_length=100)),
                ('estadoCompra', models.CharField(choices=[('PENDIENTE', 'Esperando Entrega'), ('RECIBIDO', 'Entregado y Recibido')], default='PENDIENTE', max_length=20)),
                ('domiciliario', models.PositiveIntegerField()),
                ('fechaEntrega', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
