# Generated by Django 4.2.1 on 2023-06-18 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventario', '0005_alter_bodega_fecha'),
        ('Facturacion', '0002_delete_devoluciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='productos',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productocompra_set', to='Facturacion.pagos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.productos')),
            ],
        ),
    ]
