# Generated by Django 4.1.7 on 2023-06-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_remove_pagos_productos_alter_pagos_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='caja',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pagos',
            name='descuento',
            field=models.IntegerField(default=0),
        ),
    ]
