# Generated by Django 4.2.1 on 2023-06-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0004_pagos_caja_pagos_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoCaja', models.PositiveIntegerField()),
                ('numeroCaja', models.PositiveIntegerField()),
                ('Estado', models.CharField(choices=[('Habilitada', 'Esta en Servicio'), ('Deshabilitada', 'No esta en Servicio')], default='Habilitada', max_length=20)),
                ('Efectivo', models.PositiveIntegerField()),
            ],
        ),
    ]
