# Generated by Django 4.1.7 on 2023-06-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_clientes_carritocompras'),
        ('Facturacion', '0006_alter_cajas_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('codigoOrden', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('metodoPago', models.CharField(default='', max_length=100)),
                ('fechaCreacion', models.DateTimeField()),
                ('estado', models.CharField(default='', max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes')),
            ],
        ),
    ]
