# Generated by Django 4.2.1 on 2023-06-20 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0007_ordenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('codigoMovimiento', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Movimiento', models.CharField(max_length=20)),
                ('Efectivo', models.PositiveIntegerField()),
                ('Motivo', models.CharField(max_length=100)),
                ('fecha', models.CharField(default=1, max_length=15)),
                ('Caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Facturacion.cajas')),
            ],
        ),
    ]
