# Generated by Django 4.2.1 on 2023-06-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0009_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='fecha',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
