# Generated by Django 4.1.7 on 2023-06-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0011_compras_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='descuento',
        ),
    ]
