# Generated by Django 4.1.7 on 2023-06-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0012_remove_pagos_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocompra',
            name='id',
        ),
        migrations.AddField(
            model_name='productocompra',
            name='codigoProductoCompra',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='productocompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
