# Generated by Django 4.1.7 on 2023-06-21 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Facturacion', '0013_remove_productocompra_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='domiciliario',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='estadoCompra',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='fechaEntrega',
        ),
        migrations.AlterField(
            model_name='pagos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='metodoPago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='precioTotal',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
