# Generated by Django 4.1.7 on 2023-06-21 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_clientes_telefono'),
        ('Facturacion', '0017_alter_pagos_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes'),
        ),
    ]
