# Generated by Django 4.1.7 on 2023-06-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0019_alter_pagos_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='caja',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
