# Generated by Django 4.1.7 on 2023-06-21 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0022_compras_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='caja',
        ),
    ]
