# Generated by Django 4.1.7 on 2023-06-21 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0023_remove_compras_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facturacion.cajas'),
        ),
    ]
