# Generated by Django 4.1.6 on 2023-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tokenUsed',
            field=models.BooleanField(default=False),
        ),
    ]
