# Generated by Django 4.1.7 on 2023-06-19 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_clientes_token_clientes_tokenused'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='carritoCompras',
        ),
    ]
