# Generated by Django 4.1.7 on 2023-06-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_clientes_carritocompras'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='telefono',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
