# Generated by Django 4.1.7 on 2023-06-17 22:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_alter_bodega_fecha_alter_bodega_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 17, 17, 2, 31, 161754)),
        ),
        migrations.AlterField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.bodega'),
        ),
    ]
