# Generated by Django 4.1.7 on 2023-06-19 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_alter_bodega_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodega',
            old_name='cantidad',
            new_name='cantidadProducto',
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 8, 58, 39, 875045)),
        ),
    ]
