# Generated by Django 4.1.7 on 2023-06-19 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_rename_cantidadproducto_bodega_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('codigoCategorias', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=50)),
                ('imagenCategoria', models.ImageField(null=True, upload_to='Categorias/')),
            ],
        ),
        migrations.AlterField(
            model_name='bodega',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 11, 29, 23, 479978)),
        ),
    ]
