# Generated by Django 4.1.7 on 2023-06-19 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_alter_bodega_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2023, 6, 19, 16, 16, 10, 335916)),
        ),
    ]
