# Generated by Django 4.1.7 on 2023-06-14 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reseñas',
            fields=[
                ('codigoReseña', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cliente', models.PositiveIntegerField()),
                ('producto', models.PositiveIntegerField()),
                ('reseña', models.CharField(max_length=1000)),
                ('fechaPublicacion', models.DateTimeField()),
                ('valoracionProducto', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
