# Generated by Django 4.1.7 on 2023-06-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_alter_bodega_fecha'),
        ('Usuarios', '0002_clientes_token_clientes_tokenused'),
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes'),
        ),
        migrations.AlterField(
            model_name='reseñas',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.productos'),
        ),
    ]
