# Generated by Django 4.1.7 on 2023-06-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_reseñas_cliente_alter_reseñas_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseñas',
            name='codigoReseña',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
