# Generated by Django 4.1.7 on 2023-06-19 23:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_clientes_carritocompras'),
        ('Inventario', '0014_alter_bodega_fecha'),
        ('Tienda', '0003_alter_reseñas_codigoreseña'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('codigoReseña', models.AutoField(primary_key=True, serialize=False)),
                ('reseña', models.CharField(max_length=1000)),
                ('fechaPublicacion', models.DateTimeField()),
                ('valoracionProducto', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.clientes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.productos')),
            ],
        ),
    ]
