# Generated by Django 4.1.7 on 2023-06-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_carritocompras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritocompras',
            old_name='codigoReseña',
            new_name='codigoCarrito',
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='fechaPublicacion',
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='reseña',
        ),
        migrations.RemoveField(
            model_name='carritocompras',
            name='valoracionProducto',
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carritocompras',
            name='precioTotal',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
